openapi: "3.0.0"
info:
  title: "OpenAPIサンプル"
  description: "サンプル情報取得API"
  version: "1.0.0"
servers:
  - url: http://localhost:5000
    description: ローカル環境
paths:
  /sample:
    get:
      tags:
        - 動作確認用
      summary: 動作確認用サンプルAPI
      parameters:
        - in: query
          name: id
          description: "サンプルid"
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SampleResponses"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    SampleResponses:
      type: array
      items:
        type: object
        properties:
          sampleId:
            description: サンプルID
            type: integer
            nullable: false
          message:
            description: メッセージ
            type: string
            nullable: false
    ErrorModel:
      description: エラー情報
      type: object
      properties:
        error_message:
          description: エラーメッセージ
          type: string
          example: "バリデーションエラー：パラメータが正しくありません。"
  responses:
    "400":
      description: パラメータ不正時のエラーレスポンス
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorModel"
    "403":
      description: APIキー認証失敗時のエラーレスポンス
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorModel"
    "404":
      description: パスが存在しない場合のエラーレスポンス
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorModel"
    "500":
      description: サーバ内部エラー、同時実行上限超過時のエラーレスポンス
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorModel"
